Feat/editor
YazykovaDaria/graphiql-app pull request #21
Opened 2023-05-20 19:13 UTC by YazykovaDaria

1. Добавлены стили  для главной страницы
![Снимок экрана от 2023-05-20 22-09-55](https://github.com/YazykovaDaria/graphiql-app/assets/93446641/b896e30a-2b90-4eac-86c5-7061162d08bf)

3. Настроен стор для редактора и для тестов
4. Добавлены интпуты для ввода данных запроса и переменных
5. Добавлен хук useAutoComplete для авто закрывания скобок в инпутах

Иногда в консоли появляются ошибки mui из-за слишком длинного placeholder в компоненте editor

Нужно дописать тесты

2023-05-26 16:52 UTC, Doooodie requested changes

2023-05-26 16:52 UTC, Doooodie commented on package.json
> +    "@esbuild/linux-x64": "^0.17.18",
Нужно убрать эту зависимость, так как у проверяющих из-за неё может не запуститься проект

2023-05-26 16:52 UTC, Doooodie commented on src/components/docsExplorer/DocsExplorer.tsx
> +// костя, это просто пример запроса, я не уверена что тут есть все нужные данные, смотри нужную схему в документашке апи
Эти комментарии можно убрать, вместо них создать issue
Если комментарий необходим, то тогда на английском языке

2023-05-26 16:52 UTC, Doooodie commented on src/components/docsExplorer/DocsExplorer.tsx
> +      console.log(docs);
Консоль логов в продакшене быть не должно

2023-05-26 16:52 UTC, Doooodie commented on src/components/editor/Editor.test.tsx
> +  // it('should auto complete closed bracket', () => {
Нужно дописать тест либо убрать комментарии

2023-05-26 16:52 UTC, Doooodie commented on src/components/variablesSection/Variables.test.tsx
> +// import userEvent from '@testing-library/user-event';
Убрать комментарии

2023-05-26 16:52 UTC, Doooodie commented on src/store/slices/editorSlice.ts
> +/* eslint-disable no-param-reassign */
Нужно убрать это правило
Чтобы ошибок не было, в eslint конфиг добавляем это правило: `"no-param-reassign": ["error", { "props": false }]`

2023-05-26 16:52 UTC, Doooodie commented on src/store/slices/responseSectionSlice.ts
> +/* eslint-disable no-param-reassign */
Нужно убрать это правило

2023-05-26 22:08 UTC, ivan52945 approved these changes

2023-05-27 15:34 UTC, Doooodie requested changes

2023-05-27 15:34 UTC, Doooodie commented on src/components/docsExplorer/DocsExplorer.tsx
> +      alert(JSON.stringify(docs));
Убрать алерт

2023-05-27 16:00 UTC, YazykovaDaria commented on src/components/docsExplorer/DocsExplorer.tsx
> +      alert(JSON.stringify(docs));
алерт пока оставлю, если смогу сделать доку - не будет конфликта при слиянии, если нет - компонент нигде не используется

2023-05-27 16:10 UTC, Doooodie approved these changes

2023-05-27 16:10 UTC, merged