App structure
YazykovaDaria/graphiql-app pull request #9
Opened 2023-05-03 21:40 UTC by ivan52945

Adding general structure
without effets

2023-05-25 19:48 UTC, YazykovaDaria commented on src/hocs/AuthProvider.tsx
чтобы отличать хоки от обычных компонентов при импорте их именование обычно начинают с with (withAuthProvider)

2023-05-25 19:48 UTC, YazykovaDaria commented on src/components/langSwitcher/LangSwitcher.tsx
валится тест на этот компонент, т.к. ты изменил логику смены языка и компонент select на iconButton, нужно поправить тест под текущую логику.
В этом проекте не критично, но с точки зрения расширяемости (добавления новых языков) код стал хуже

2023-05-25 19:48 UTC, YazykovaDaria commented on src/pages/welcome/WelcomePage.tsx
чтобы не захломлять компонент, лучше создать в этой же папке файл const и вынести туда const members и const explList

2023-05-26 17:12 UTC, Doooodie requested changes

2023-05-26 17:12 UTC, Doooodie commented on src/index.css
>  body {
css файлов быть не должно. Все стили можно прописать в теме, если необходимо

2023-05-26 17:12 UTC, Doooodie commented on src/components/Header.tsx
> +          <IconButton sx={{ borderRadius: 2, color: 'inherit', columnGap: '5px' }}>
Переключение темы не работает. Нужно либо сделать переключение темы, либо убрать кнопку

2023-05-26 17:12 UTC, Doooodie commented on src/components/Header.tsx
> +          <Typography component='h1'>RS React GraphQL</Typography>
В хедере нет возможности перейти на лендинг. Я бы сделал этот заголовок ссылкой на лендинг

2023-05-26 17:12 UTC, Doooodie commented on src/app/router/Router.tsx
> +// import { AuthProvider } from '../../hocs/AuthProvider';
Убрать комментарии

2023-05-26 17:12 UTC, Doooodie commented on src/components/Header.tsx
> +    <HideOnScroll>
В требованиях указано не прятать хедер при скролее, а менять его цвет или размер

2023-05-26 17:12 UTC, Doooodie commented on src/hocs/RequireAuth.tsx
> +export function RequireAuth({ children }: IRequireAuth) {
В требованиях указан редирект на главную с роутов авторизации, если юзер авторизован. Тут этого нет

2023-05-26 17:12 UTC, Doooodie commented on src/pages/main/MainPage.tsx
>  // it's just example, delete it if you need
Убрать комментарии

2023-05-26 17:37 UTC, ivan52945 commented on src/components/Header.tsx
> +    <HideOnScroll>
цвет или размер это как пример
главное, чтобы был анимирован

2023-05-27 13:48 UTC, YazykovaDaria approved these changes

2023-05-27 15:29 UTC, Doooodie approved these changes

2023-05-27 15:31 UTC, merged